- name: "RHV: HE Backup"
  hosts: all
  become: yes
  gather_facts: false
  tags: he-backup

  vars_files:
    - ./roles/vars/engine_vars.yml
    - ./roles/vars/nfs.yml
    - ./roles/vars/telegram.yml

  vars:
    retention_days: 1w

  roles:
    - he-backup
