- name: "RHV: HE Backup"
  hosts: all
  become: yes
  gather_facts: false
  tags: he-backup

  vars_files:
    - engine_vars.yml
    - nfs.yml
    - telegram.yml

  vars:
    retention_days: 1w

  roles:
    - he-backup
